### PR TITLE
migrate cjsx to jsx

### PR DESCRIPTION
**Pull request by reimertz**
What a sh*tshow this was!

Here it is, a complete and working migration from coffescript-jsx to regular es6-jsx.

Since there is no test, I would be very glad if we all could help out making sure this doesn't break anything.

### CODE REVIEW

**Comment by reimertz** [comment]
Actually, I will have to fix a thing. I forgot to beautify the JSX syntax, so now, there all one line.

**Comment by michelson** [comment]
this is great! I will have to learn es6 now 😁
I will do some QA asap to check everything is working
thanks for this contribution @reimertz :1st_place_medal: !

**Comment by reimertz** [comment]
Updated jsx syntax and pointed main in package.json to App.jsx. 

This might actually solve #8, let me check.

cc @levbrie

**Comment by michelson** [comment]
Hi @reimertz ! 

I've done some QA, is almost everything working I just found only one error when I try to use the embed buttons for links or video, specifically it seems that the placeholder class is not properly exported (or imported) 

image

ps: I will miss the `@` 😂

**Comment by reimertz** [comment]
@michelson oh derp!

fixed in https://github.com/michelson/dante2/pull/19/commits/1a3b219a56ec5c1b1d615cc15d56f7784531d34b

**Comment by reimertz** [comment]
I feel you regarding '@ vs. this'. There is a bunch of babel transforms that can fix this if you find it to be to much of a problem.

`this.awesomeFunction = this.awesomeFunction.bind(this)` can be fixed with `"es7.classProperties`. more info here -> http://www.ian-thomas.net/autobinding-react-and-es6-classes/

**Comment by michelson** [comment]
Hi @reimertz , it seems it's passing my QA! 
I only need to ensure that is working on my own integration :)
are we ready to merge ?

**Comment by reimertz** [comment]
I think so!

**Comment by reimertz** [comment]
@michelson  once this is merged, I have a pr for header support.

**Comment by levbrie** [comment]
@reimertz Regarding #8 have you tried importing and using as a component?

I'm on https://github.com/reimertz/dante2/commit/ea7e76645a04d5ea012e4db4ab5fd28ab643d245 and am getting

```sh
ERROR in ./~/Dante2/app/components/App.jsx
Module parse failed: <path_to_node_modules>/node_modules/Dante2/app/components/App.jsx Unexpected token (255:6)
You may need an appropriate loader to handle this file type.
```

Lines 253-8 are as follows at this commit:

```js
  render() {
    return this.editor = ReactDOM.render(
      <DanteEditor content={this.getContent()} config={this.options} />,
      document.getElementById(this.options.el)
    )
  }
```

I haven't actually used React in this way since it isn't generally desirable to render components this way, so I'm not sure if this is actually a parsing issue or there's something else going on.  If you have used the editor directly as a component, are you still using an element reference?  Would you mind sharing?  And perhaps there should be an option to render directly without using a DOM element reference.

**Comment by reimertz** [comment]
@levbrie yep, this is an issue right now. @michelson is building the transpiled version of dante into /docs which includes all dependencies such as react, axios etc.

That is why I created https://github.com/michelson/dante2/issues/24. Dante needs to have separate builds for dists, es6 modules etc.

**Comment by levbrie** [comment]
@reimertz agreed.  Great job on migrating to jsx by the way.  Makes a huge difference just looking through the code.

**Comment by reimertz** [comment]
@levbrie thanks homie, we can solve these issues together! 💪

**Comment by levbrie** [comment]
@reimertz Awesome, i like the sound of that.  @michelson @reimertz What I was thinking was that it might make sense to create an index.js file to serve as the main file.  `index.js` would only be responsible for exporting the functions, objects, and primitives that ought to be directly available to the user.  Then we could split `App.jsx` up into a `Dante.js` and a `DanteEditor.jsx` (I usually just `.js` for `.jsx` files as well but I'm assuming this is the convention we're using here).  `Dante.js` would expose the `Dante` class for users who want to use Dante2 outside of React (i.e. the way it's currently set up) and `DanteEditor` would expose the `DanteEditor` component, which we could refactor to take in the same options as the `Dante` class as props, so we'd up with something like:

`index.js`

```js
export DanteEditor from './components/DanteEditor';
import Dante from './Dante';
export default Dante; // or whichever you decide ought to be the default
```

`DanteEditor.jsx` 

```js
export default class DanteEditor extends Component {
  // etc.
}
```

`Dante.js` 

```js
export default class Dante {
  // etc.
}
```

Off the top of my head it seems like it might be a reasonable approach to maintaining the current API and extending it to enable direct integration with React.

**Comment by reimertz** [comment]
@levbrie deff. like the idea of spitting up App.jsx. 

But I still think we would need to have separate build for the lib and es6 mobule, right? Because the lib needs all the dependencies build with it, whereas the es6 module need 'lossy' imports. 

I am still a bit of a noob when it comes to webpack.v2, so please correct me if I am wrong.

**Comment by michelson** [comment]
Hi Guys, 
Great work @reimertz ! tested with the latest changes on a rails app, all working as expected, 
let's do this

**Comment by levbrie** [comment]
@reimertz sorry i was away.  You're absolutely right - there should be separate builds for the lib and for using it with react - and the react build shouldn't build any of the dependencies.

**Pull request merged**
