### PR TITLE
modules support

### PR DESCRIPTION
**Pull request by michelson**
+ Add build tools for npm , es , bower, lib
+ Separate demo app from main lib
+ move `app` to `src`

usage: 

+ `yarn build`

related #24

### CODE REVIEW

**Comment by reimertz** [comment]
Dope! 🎉👏🏻😍

**Comment by reimertz** [comment]
It seems you copy-pasted/got inspired a lot by ReactBootstrap. Wonder if you maybe should add some credit/note about that? :)

**Comment by reimertz** [comment]
Also, it seems css is missing from each built package.

**Comment by michelson** [comment]
@reimertz yes, I've used the build tools from ReactBoostrap I will add the proper credit to them 👍

**Comment by michelson** [comment]
Ok , I think we got it.
I used the build tools from ReactBootstrap + expose-loader in order to make available `Dante` & `DanteEditor` on window. 
By default node package will create a `Dante2` global variable which will contain `Dante` and `DanteEditor` too as properties.

### modules
+ For Ruby we will use `dist` and assets from `src`
+ es modules will be in ./es
+ amd modules on ./amd
+ npm modules on ./lib
+ docs for gh-pages on ./docs (loading an specific files from ./demo. Demo & library has been decoupled)
+ css & fonts assets are exported on `dist` & `amd` (don't know if it's necessary to export them on `lib` or `es` )

**Comment by reimertz** [comment]
got these errors when trying to build

```
reimertz at reimertz-tsu in ~/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2 (master●●)
$ yarn
yarn install v0.18.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 12.48s.

reimertz at reimertz-tsu in ~/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2 (master●●)
$ yarn build
yarn build v0.18.1
$ babel-node tools/build-cli.js
Building: npm module
Building: es module
Building: bower module
Building: distributable
Building: docs
Built: es module
Built: npm module
Error: Command failed: webpack --bail -p
Error
    at NormalModule.<anonymous> (/Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/webpack/lib/NormalModule.js:113:20)
    at NormalModule.onModuleBuild (/Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
 `webpack --bail -p` (exited with error code 1)
    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
error Command failed with exit code 1.
```

**Comment by reimertz** [comment]
Also, styles are not added in any of the build folders which causes errors on import.

```

import Dante from './components/dante';
import DanteEditor from './components/dante_editor';
import dantecss from './styles/dante.scss';
import draftcss from './styles/draft.css';

module.exports = {
  Dante: Dante,
  DanteEditor: DanteEditor
};
```

```
Failed to compile.

Error in ./~/Dante2/lib/index.js
Module not found: ./styles/dante.scss in /Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/lib

 @ ./~/Dante2/lib/index.js 11:14-44

Error in ./~/Dante2/lib/index.js
Module not found: ./styles/draft.css in /Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/lib

 @ ./~/Dante2/lib/index.js 15:13-42
```

**Comment by michelson** [comment]
Hi @reimertz , uhm that's odd, 
in src do you see the styles folder ?

**Comment by michelson** [comment]
can you do `yarn install` and then `yarn build` and see what happens ?

**Comment by reimertz** [comment]
@michelson that is what I did in the previous steps.

**Comment by michelson** [comment]
uhm, weird, we use the same yarn version, but my builds are just fine.
the --bail option will crash completely , it seems that the problem is on the style loading on src/index as you said , maybe you could try to comment those styles imports and build again and tell us what's the result.


```
$ yarn build
yarn build v0.18.1
$ babel-node tools/build-cli.js
Building: npm module
Building: es module
Building: bower module
Building: distributable
Building: docs
Built: npm module
Built: es module
Built: bower module
Built: docs
Built: distributable
✨  Done in 37.51s.
```

**Comment by michelson** [comment]
@reimertz I've build this on another machine with node 4.4.5 and is working fine too, I've no idea why is not working for you

**Comment by reimertz** [comment]
```
$ npm -v;node -v; yarn version
3.10.9
v7.1.0
yarn version v0.18.1
```

**Comment by reimertz** [comment]
```
$ npm -v;node -v; yarn version
2.15.9
v4.6.0
yarn version v0.18.1
```

error
```
$ yarn build
yarn build v0.18.1
$ babel-node tools/build-cli.js
Building: npm module
Building: es module
Building: bower module
Building: distributable
Building: docs
Built: es module
Built: npm module
Error: Command failed: /bin/sh -c webpack --bail -p
ModuleParseError: Module parse failed: /Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/src/index.js Line 2: Unexpected token
You may need an appropriate loader to handle this file type.
|
| import Dante from './components/dante'
| import DanteEditor from './components/dante_editor'
|
    at DependenciesBlock.<anonymous> (/Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/webpack/lib/NormalModule.js:113:20)
    at DependenciesBlock.onModuleBuild (/Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/reimertz/fux/projects/anolog/repos/www.anolog.org/node_modules/Dante2/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
 `webpack --bail -p` (exited with error code 1)
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)
error Command failed with exit code 1.
```

**Comment by reimertz** [comment]
This is interestingly the same error i get if I import Dante as  `import { Dante } from 'Dante2/es/'`

**Comment by michelson** [comment]
@reimertz are you building dante2 inside another project ? or directly from source ? 
it seems the error you describe is generated when building inside another project from node_modules, but I don't see the difference from the main source whit the installed via node_modules.

**Comment by reimertz** [comment]
@michelson I am building inside of node_modules since there isn't a published build yet. I could try to symlink the repo into node_modules instead.

**Comment by michelson** [comment]
@reimertz , sorry for the delay! I've uploaded a testing repo which works with this branch ( distribution )
I think the problem was the loading of styles, I've removed that dependency outside the Dante/DanteEditor components to another file

check the example here https://github.com/michelson/dante2-tests/settings , let me know if it's working for you.

**Comment by michelson** [comment]
merged & released as 0.3.1 🎉

**Pull request merged**
